[build]
builder = "nixpacks"
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar target/*.jar --spring.profiles.active=prod"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
