[build]
builder = "nixpacks"
buildCommand = "dotnet restore SuperAdmin.API/SuperAdmin.API.csproj && dotnet publish SuperAdmin.API/SuperAdmin.API.csproj -c Release -o out"

[deploy]
startCommand = "dotnet out/SuperAdmin.API.dll"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
